cloud-native-toolkit/iascable

examples/common-services.yaml
examples/ocp-management.yaml
src/models/bill-of-material.model.spec.ts
src/models/bill-of-material.model.ts
src/models/catalog.model.spec.ts
src/models/catalog.model.ts
src/models/module.model.ts
src/models/stages.model.ts
src/models/variables.model.ts
src/services/iascable.impl.ts
src/services/module-selector/module-selector.impl.spec.ts
src/services/module-selector/module-selector.impl.ts
src/services/module-selector/selected-modules.model.ts
src/services/terraform-builder/terraform-buiilder.impl.spec.ts
src/services/terraform-builder/terraform-builder.api.ts
src/services/terraform-builder/terraform-builder.impl.ts
src/util/array-util.ts
src/util/logger/logger.api.ts
src/util/logger/noop-logger.impl.ts
src/util/version-resolver/version-resolver.ts
test/catalog.yaml

- Use the module names as an identifier in the BOM as an alternaive to the module source
- Support Terraform containing multiple instances of the same modules
- Support module providing an alias to distinguish multiple instances of the same module
- Allow selected modules to define which dependency instance to use via the defined alias, particularly in the event there are multiple instances of the same module. E.g. 3 different namespace instances defined, each with a different value; allow tool modules to select which namespace they use
- Allow selected modules to define values for their variables
- Adds example boms that utilize these features

Overhauls module handling for Terraform generation

---

src/errors/bill-of-material.error.ts
src/services/module-selector/module-selector.api.ts
src/services/module-selector/module-selector.impl.spec.ts
src/services/module-selector/module-selector.impl.ts

- Parses BOM module config to check for errors
- Validates that the module exists in the catalog
- Validates that defined variables match values on the provided module
- Validates that defined dependencies match values on the provided module

Adds validateBillOfMaterialModuleConfigYaml

---

ref-arch/140-mzr-workload-openshift.yaml
src/services/bill-of-material-builder/bill-of-material-builder.ts

- Fixes ssh key references
- Sets alias for name_prefix variable in management-vpc module
- Adds logic to use shorthand for ref arch names

Updates workload-openshift ref architecture

---

ref-arch/000-account-setup.yaml
ref-arch/100-shared-services.yaml
ref-arch/110-mzr-management.yaml
ref-arch/120-mzr-management-openshift.yaml
ref-arch/130-mzr-workload.yaml
ref-arch/140-mzr-workload-openshift.yaml
ref-arch/150-openshift.yaml
ref-arch/165-openshift-workload.yaml
ref-arch/170-openshift-argocd.yaml
src/services/iascable.impl.ts

- Adds 000 ref arch and removes activity-tracker from 100
- Adds default values for onboard-fs-account module
- Adds gateways to subnets and sets allowed_ip for bucket
- Updates default catalog to modules.cloudnativetoolkit.dev
- Removes acl_rules from BOM (should not be needed)
- Fixes resource_locations for activity tracker instances
- Updates allowed_ip value and hpcs_name_prefix
- Adds vpc-gateway to worker subnets
- Removes (incorrect) image_name from vpn server
- Removes public gateway from vpn-subnets
- Removes authorize-kms from BOMs

Updates to reference architectures for rc3

---

examples/baseline-ocp.yaml
ref-arch/000-account-setup.yaml
ref-arch/100-shared-services.yaml
ref-arch/110-mzr-management.yaml
ref-arch/120-mzr-management-openshift.yaml
ref-arch/130-mzr-workload.yaml
ref-arch/140-mzr-workload-openshift.yaml
ref-arch/170-openshift-argocd.yaml

Updates reference architectures to allow flexibility in footprint
- Replaces hpcs and key protect modules with ibm-kms module to provide a choice between key protect and hpcs
- Creates service authorizations for both hpcs and key protect
- Exposes worker_count variable as mgmt_worker_count and workload_worker_count to allow them to be configured independently
- Exposes worker-subnet__count variable as mgmt_worker_subnet_count and workload_worker_subnet_count to allow them to be configured independently
- Updates 170-openshift-argocd variable names to `login_user` and `login_password` (see #65)
- Updates BOMs with descriptive labels and annotations
Co-authored-by: Noé Samaille <noe.samaille@ibm.com>

 Updates reference architectures to allow flexibility of deployed size

---

src/services/terraform-builder/terraform-builder.impl.ts

make required variables optional when the module (dependency) is optional

make required variables optional if dep is optional

---

package.json
scripts/launch.sh
src/commands/iascable-build.ts

- Updates build process to pick up file
- Moves launch.sh to root ot output directory instead of BOM output dir
Co-authored-by: Noé Samaille <noe.samaille@ibm.com>

Fixes launch script in output

---

scripts/apply.sh
scripts/destroy.sh
src/commands/iascable-build.ts
src/models/stages.model.ts
src/services/iascable.impl.ts
src/services/terraform-builder/terraform-builder.new.ts

- Generates output directory as writable to all
- Updates variables section in generated bom to include variables and values included in auto.tfvars
- Adds apply and destroy scripts to generated bundle

Updates to generated output

---

src/services/catalog-loader/catalog-loader.impl.ts
src/services/terraform-builder/terraform-builder.new.ts

- Applies JSON.parse() on variable default values if the variable type is not string but the value is a string
closes #73

Handles JSON parsing error of default values

---

src/commands/iascable-build.ts
src/commands/inputs/iascable.input.ts
src/services/iascable.api.ts
src/services/iascable.impl.ts

- The `-i` or `-r` and `--name` arguments can be provided multiple times to generate terraform from multiple BOMs at one time. E.g.
```shell
isacable -i ./bom1.yaml -i bom2.yaml -o myoutput
```
- Removes arguments for interactive mode of the cli
closes #149

Adds support for multiple input BOMs in one call

---

launch.sh
scripts/launch.sh
src/commands/iascable-build.ts

- Refreshes launch script included in generated terraform with updated image and fixes to docker run logic
closes #164

Fixes issues with launch script

---

examples/baseline-ocp2.yaml
src/commands/iascable-build.ts

The `path` annotation puts the generated terraform in a path relative to the `output` folder. 
For example:
```yaml
apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
name: baseline-ocp-vpc2
annotations:
path: test
spec:
modules:
- name: ibm-ocp-vpc
- name: openshift-cicd
variables: []
```
Because of the `path: test` annotation, this BOM will output the generated terraform into a folder named `{output dir}/test/baseline-ocp-vpc2` instead of `{output dir}/baseline-ocp-vpc2` as it would by default.
This example is also provided in `examples/baseline-ocp2.yaml`
closes #166 

Adds support for path annotation in BOM

---

.github/workflows/release.yaml
README.md
package.json
src/models/catalog.model.spec.ts
src/models/catalog.model.ts
src/models/module.model.ts
src/moduleIdAliases.yaml
src/services/catalog-loader/catalog-loader.impl.ts
src/services/module-selector/selected-modules.resolver.spec.ts
src/services/module-selector/selected-modules.resolver.ts
test/catalog.yaml

- Adds support for aliases entry in catalog with mapping from current id to previous ids
- Adds workflow job to publish install.sh to gh-pages
- Updates readme with simplified install steps
closes cloud-native-toolkit/software-everywhere#366

Handles relocated modules

---

.github/workflows/asset-publish.yaml
README.md
install.sh

- Updates asset names and install.sh to be backwards compatable - closes #181

Fixes issues installing back-level versions of cli

---

scripts/apply.sh

removes `"` from parse of environment variable as `launch.sh` now strips these

Interim fix to env parse

---

src/models/file.model.ts
src/models/stages.model.ts
src/services/iascable.impl.ts
src/services/module-documentation/module-documentation.ts
src/services/terraform-builder/terraform-buiilder.impl.spec.ts
src/services/terraform-builder/terraform-builder.api.ts
src/services/terraform-builder/terraform-builder.new.ts

When using a private repo on github.com, iascable cannot read README.md since it requires a GitHub token. Since the README.md is only downloaded to copy the documentation, I changed the code to ignore the error and continue with the output directory creation.

ignore error when reading private repo readme

---

scripts/apply.sh

Updates logic in `apply.sh` when parsing the generated `bom.yaml` with the same yq/jq formatting used when parsing `variables.yaml`. 
fixes #216 

handle complex types in first apply run

---

src/services/catalog-loader/catalog-loader.impl.ts

Avoids removing leading `/` in a path provided to a catalog before reading the file.
fixes #225 

keep leading slash in catalog file path

---

src/models/catalog.model.ts
src/models/crd.model.ts
src/models/module.model.ts
src/services/catalog-loader/catalog-loader.impl.ts
src/services/module-selector/module-selector.impl.spec.ts
src/services/module-selector/selected-modules.resolver.spec.ts
test/catalog.yaml

- Allows module metadata file to be passed as input for catalog url instead of requiring a full catalog
closes #212

Adds support for module metadata as catalog input

---

src/commands/iascable-build.ts
src/commands/iascable-docs.ts
src/commands/support/middleware.ts

- The default catalog url (https://modules.cloudnativetoolkit.dev/index.yaml) is added as the first catalog in the list if it is not explicitly provided as input
closes #231

Updates catalogUrls to include base catalog by default

---

src/models/stages.model.ts
src/services/catalog-loader/catalog-loader.impl.ts

- Uses 'name' attribute to test module uniqueness in catalog instead of id
- Puts new modules before existing catalog modules in list so new modules are selected when there are duplicates
- Removes '?ref={version}' if the id is a 'file:' url
closes #240

Fixes catalog logic to ensure custom modules override base catalog

---

.gitignore
src/models/variables.model.ts

- Adds required `features {}` block to Azure terraform provider block - closes #171

Fixes configuration of azurerm provider block

---

examples/api-mgmt-solution.yaml
src/commands/iascable-build.ts
src/models/layer-dependencies.model.ts
src/models/solution.model.ts
src/models/terragrunt.model.ts
src/services/iascable/iascable.impl.ts
src/util/array-util/flatten.ts

- Detect if a layer provides storage capabilities by checking for modules that implement the cluster-storage interface
- Detect if a layer needs storage capabilities by checking for the storage manager module or storage-consumer inteface
- Add annotations to the BOM to name the module alias in the layer that provides the capability to generate the variable names correctly instead of hard coding them
closes #299

Fix auto-wiring of storage dependencies between solution layers

---

package-lock.json
src/commands/iascable-build.ts
src/commands/iascable-print.ts
src/model-impls/catalog.impl.ts
src/model-impls/stages.impl.ts
src/model-impls/variables.impl.ts
src/models/catalog.model.ts
src/models/file.model.ts
src/models/module.model.ts
src/models/variables.model.ts
src/services/catalog-loader/catalog-loader.api.ts
src/services/catalog-loader/catalog-loader.impl.ts
src/services/iascable/iascable.api.ts
src/services/iascable/iascable.impl.ts
src/services/module-documentation/module-documentation.ts
src/services/module-metadata-service/module-metadata-service.ts
src/services/terraform-builder/terraform-builder.new.ts
src/util/bill-of-material-builder/bill-of-material-builder.ts
src/util/bundle-writer/bundle-writer.api.ts
src/util/bundle-writer/bundle-writer.fs.ts
src/util/bundle-writer/bundle-writer.zip.ts

- Allows passing local module.yaml in catalog parameter of build to register local module version
- Allows passing local bom or solution bom file in catalog parameter of build to register local bom when generating solution
closes #305

Adds support for local modules, boms, and solution boms when building

---

src/services/iascable/iascable.impl.ts

- Default basePath to '.' if not provided - closes #307

Fix bundle writing when optional basePath not provided
