cloud-native-toolkit/iascable

- src/commands/iascable-build.ts
- src/models/file.model.ts
- src/models/module.model.ts
- src/models/stages.model.ts
- src/models/tile.model.ts
- src/services/catalog-loader/catalog-loader.impl.ts
- src/services/terraform-builder/terraform-builder.impl.ts
> Inckudes module readmes in output files

- src/models/file.model.ts
- src/models/stages.model.ts
- src/models/tile.model.ts
> Updates file contents return type

- src/commands/iascable-build.ts
- src/models/catalog.model.ts
- src/models/variables.model.ts
> Cleans up the generation of terraform variables file

- src/models/variables.model.ts
- Handles list() and object() types properly
- Makes everything a string at the outer level and transforms into the appropriate type in the stage
> Updates terraform variable handling

- src/services/iascable.impl.ts
- src/services/terraform-builder/terraform-buiilder.impl.spec.ts
- src/services/terraform-builder/terraform-builder.api.ts
- src/services/terraform-builder/terraform-builder.impl.ts
> Removes unnecessary billofmaterial input from terraform builder

- src/commands/iascable-build.ts
- src/errors/bill-of-material.error.ts
- src/errors/index.ts
- src/models/bill-of-material.model.ts
- src/services/bill-of-material-builder/bill-of-material-builder.ts
- src/services/bill-of-material-builder/index.ts
- src/services/index.ts
> Adds helper functions to parse bom yaml

- src/services/module-selector/selected-modules.model.ts
- src/services/terraform-builder/terraform-builder.impl.ts
> Sorts module list before resolving modules

- src/models/variables.model.ts
> Uses bool and number variable return types

- src/models/variables.model.ts
> Removes transformation logic for bool variables

- src/commands/iascable-build.ts
- src/commands/inputs/iascable.input.ts
- src/models/variables.model.ts
> Removes empty string from list after splitting string

- README.md
- examples/common-services.yaml
- examples/ocp-management.yaml
> Updates readme for usage

- examples/ocp-management.yaml
- src/commands/iascable-build.ts
- src/models/bill-of-material.model.ts
- src/models/stages.model.ts
- src/models/variables.model.ts
- src/services/iascable.impl.ts
- src/services/terraform-builder/terraform-builder.api.ts
- src/services/terraform-builder/terraform-builder.impl.ts
- Adds support for providing description, alias, required, and scope fields in BOM module variables to override values from module metadata in catalog
- Adds support for providing required and value fields for global BOM variables
Addresses #28
> Updates handling of variables in BOM

- package.json
> Adds prepare script to run build before publishing

- examples/ocp-management.yaml
- examples/vpe-gateway.yaml
- src/services/module-selector/selected-modules.model.ts
- src/services/terraform-builder/terraform-builder.impl.ts
- src/util/optional.ts
- Handles empty refs array in dependencies and uses discriminator to find module
> Updates logic to support VPE Gateway

- examples/ocp-workload.yaml
- examples/transit-gateway.yaml
- src/models/module.model.ts
- src/models/variables.model.ts
- src/services/module-selector/module-selector.impl.spec.ts
- src/services/module-selector/module-selector.impl.ts
- src/services/module-selector/selected-modules.model.ts
- src/services/terraform-builder/terraform-buiilder.impl.spec.ts
- src/services/terraform-builder/terraform-builder.impl.ts
- src/util/array-util.ts
- src/util/object-util.ts
- test/catalog.yaml
Particularly to support Transit Gateway, allows a discriminator value of '*' and a type of 'list(X)' to match multiple modules and collect the result in an array.
> Support dependencies collected as array variable

- package-lock.json
- ref-arch/common-services.yaml
- ref-arch/management.yaml
- src/commands/iascable-build.ts
- src/commands/iascable-list.ts
- src/commands/iascable-print.ts
- src/commands/inputs/iascable.input.ts
- src/models/bill-of-material.model.ts
- src/services/bill-of-material-builder/bill-of-material-builder.ts
- Provides reference architecture name as a flag to the `build` command
- Provides `list` and `print` commands to interact with available reference architectures
- Addresses dependency vulnerabilities in package.json
> Adds support for using reference BOMs

- ref-arch/management.yaml
> Updates management ref-arch

- src/models/stages.model.ts
- src/models/variables.model.ts
- src/services/terraform-builder/terraform-builder.impl.ts
- Generates tfvars file for required fields and those listed in the BOM global variables
> Global variables tfvars

- src/models/stages.model.ts
- src/models/variables.model.ts
- Generates tfvar entries commented out initially
- Includes variable description as comment in the file
> Updates tfvars file generation

- ref-arch/common-services.yaml
- ref-arch/management.yaml
- ref-arch/ocp-management.yaml
- ref-arch/ocp-workload.yaml
- src/models/bill-of-material.model.ts
- src/services/terraform-builder/terraform-builder.impl.ts
> Adds support for aliases in global variables and updates ref arch

- ref-arch/common-services.yaml
> Additional update to common-services

- ref-arch/workload.yaml
> Updates variables for workload ref arch

- ref-arch/ocp-management.yaml
- ref-arch/ocp.yaml
> Sets disable_public_endpoints and kms_key_id for ocp module

- ref-arch/100-common-services.yaml
- ref-arch/110-mzr-management.yaml
- ref-arch/120-mzr-management-openshift.yaml
- ref-arch/130-mzr-workload.yaml
- ref-arch/140-mzr-workload-openshift.yaml
- ref-arch/150-openshift.yaml
- ref-arch/160-openshift-dev-tools.yaml
> Renames ref arch with indexes

- src/services/module-selector/module-selector.impl.spec.ts
- src/services/module-selector/selected-modules.model.ts
> Updates dependency resolution to handle missing optionals

- ref-arch/120-mzr-management-openshift.yaml
- ref-arch/140-mzr-workload-openshift.yaml
- ref-arch/150-openshift.yaml
> Updates openshift module config in ref architectures

- ref-arch/160-openshift-dev-tools.yaml
> Fix reference to tekton-resources module

- src/models/stages.model.ts
- src/models/variables.model.ts
- src/services/module-selector/selected-modules.model.ts
- src/services/terraform-builder/terraform-builder.impl.ts
- Treat null strings correctly
- Add logic to parse null lists of strings correctly
Fixes #55
> Updates handling of default values

- src/models/variables.model.ts
> Handles null default values for lists

- src/models/catalog.model.ts
- src/services/catalog-loader/catalog-loader.api.ts
- src/services/iascable.impl.ts
- src/services/module-selector/module-selector.api.ts
- src/services/module-selector/module-selector.impl.ts
- src/util/array-util.ts
- Includes resolved versions in output BOM
- Selects module version using the BOM version, if provided
Fixes #59
> Adds support for versions in BOM

- src/commands/iascable-build.ts
> Updates default url for module catalog

- src/commands/iascable-build.ts
> Fixes default catalog url

- src/services/terraform-builder/terraform-builder.impl.ts
> Fixes provider logic to prevent duplicates

- ref-arch/110-edge-vpc.yaml
- ref-arch/140-workload-vpc.yaml
- ref-arch/150-workload-vpc-openshift.yaml
- ref-arch/160-openshift-dev-tools.yaml
- ref-arch/165-openshift-workload.yaml
> removed references that aren't working in ascent, allow it to autowire

- src/services/terraform-builder/terraform-builder.new.ts
> Fixes missing source from required_providers block

- .github/workflows/release.yaml
> update publish gh action

- src/models/module.model.ts
- src/models/stages.model.ts
> Updates module model and StageImpl to support modules from registry

- src/services/terraform-builder/terraform-builder.new.ts
> Fixes problem of not handling global variable aliases

- README.md
- install.sh
> Adds install script and updates README to use it

- package.json
- src/commands/iascable-build.ts
> Adds launch script to built package and handle error if missing

- src/commands/iascable-build.ts
> Generates output directory as writable to all

- scripts/apply.sh
- src/commands/iascable-build.ts
> Fixes generated apply script

- src/commands/iascable-build.ts
- src/models/file.model.ts
- src/models/graph.model.ts
- src/services/dependency-graph/dependency-graph.api.ts
- src/services/dependency-graph/dependency-graph.impl.ts
- src/services/dependency-graph/index.ts
- src/services/iascable.api.ts
- src/services/iascable.impl.ts
- Generates dependencies.dot file with directed graph info (png can be generated using `graphviz` or other utilities)
> Generates dependency graph during automation build

- scripts/apply.sh
- src/commands/iascable-build.ts
Won't write sensitive values to generated variables.yaml
closes #121
> Updates generated apply script

- install.sh
> Adds progress bar for download in install script

- README.md
> Updates BOM documentation in README

- src/models/variables.model.ts
- Tests for incoming json strings for default values and parses json before stringifying
closes #142
> Fixes json encoding of default values for list of object types

- src/models/variables.model.ts
- src/services/terraform-builder/terraform-builder.new.ts
- src/util/object-util.ts
- Handles null default values
- Tries to parse default value strings as JSON if the type is list or object
closes #131
closes #132
> Handles json strings for default values in module metadata

- src/models/variables.model.ts
> Removes extra debug statement

- src/services/module-selector/selected-modules.resolver.ts
> Fixes failure to find dependency when git slug has protocol in it

- src/commands/iascable-build.ts
- Flatten flag removes terraform/ folder from output
closes #159
> Adds --flatten arg to build command

- scripts/launch.sh
> updated launch.sh to match latest in automation-solutions

- install.sh
- Changes to run in sh shell and fixes test syntax
- Adds check for curl cli
closes #157
> Fixes install.sh script on Ubuntu

- .github/workflows/asset-publish.yaml
- .github/workflows/release.yaml
- .github/workflows/verify-pr.yaml
- install.sh
- package.json
> Adds support for multi-architecture build

- .github/workflows/verify-pr.yaml
- package.json
> Updates workflow to test multi-arch build

- __mocks__/fs.js
- package-lock.json
- src/commands/iascable-build.ts
- src/util/file-util.spec.ts
- src/util/file-util.ts
> Fixes issue in chmodRecursive call

- scripts/launch.sh
version updates handling of `credentials.properties` per https://github.com/cloud-native-toolkit/automation-solutions/pull/206
> updates for launch.sh from automation-solutions

- README.md
- examples/catalog-urls.yaml
- src/commands/iascable-build.ts
- src/commands/inputs/iascable.input.ts
- src/models/catalog.model.spec.ts
- src/services/catalog-loader/catalog-loader.api.ts
- src/services/catalog-loader/catalog-loader.impl.ts
- src/services/iascable.api.ts
- src/services/iascable.impl.ts
- test/catalog.yaml
- Adds support for catalogUrls annotation
closes #185
> Allows for multiple catalogs to be provided during build

- src/commands/scripts/apply-script.ts
> updated apply script in ts file

- scripts/launch.sh
- src/commands/scripts/launch-script.ts
> updated to latest launch script

- src/commands/scripts/launch-script.ts
> Patch launch script ts syntax error

- src/commands/iascable-docs.ts
- src/commands/inputs/iascable.input.ts
- src/errors/module-not-found.error.ts
- src/models/index.ts
- src/models/module-doc.model.ts
- src/models/module.model.ts
- src/services/iascable.api.ts
- src/services/iascable.impl.ts
- src/services/module-documentation/index.ts
- src/services/module-documentation/module-documentation.api.ts
- src/services/module-documentation/module-documentation.ts
> Adds docs command to generate the readme for a module

- README.md
> Updates README with some developer documentation

- package-lock.json
- package.json
- src/commands/iascable-build.ts
- src/errors/stage-not-found.error.ts
- src/models/variables.model.ts
> Fixes error handling when dealing with multiple BOMs

- src/commands/iascable-build.ts
> Fixes error message during build

- src/commands/iascable-metadata.ts
> Handles version number for unreleased module

- scripts/apply.sh
> Updates apply script to handle extra variables added to variables.yaml

- src/commands/iascable-build.ts
- Converts warning message to debug - closes #219
> Cleans up error message when file cannot be written

- src/models/bill-of-material.model.ts
- src/models/module.model.ts
- src/models/stages.model.ts
- src/models/variables.model.ts
- src/services/terraform-builder/terraform-builder.new.ts
> Includes output.tf in generated terraform

- scripts/launch.sh
updates `cli-tools` image container version per finding in https://github.com/cloud-native-toolkit/terraform-gitops-namespace/issues/48
> Update to current launch script for cli-tools update

- src/services/catalog-loader/catalog-loader.impl.ts
> Adds module aliases if module overridden in catalog

- .github/workflows/verify-pr.yaml
> Updates verify workflow to trigger on prs on all branches

- .github/workflows/npm-publish.yaml
- README.md
> Updates tag value for npm-publish workflow

- .github/workflows/release.yaml
- README.md
- Sets filter-by-commitish on release drafter to only consider tags on this branch when calculating next tag
- Updates readme for library beta
> Fixes version numbers created by release version workflow

- package-lock.json
- package.json
- src/commands/iascable-catalog.ts
- src/services/catalog-builder/catalog-builder-service.ts
- src/services/catalog-builder/catalog-builder.api.ts
> Fixes missing dependencies

- package-lock.json
- package.json
- src/iascable.ts
- src/model-impls/index.ts
> Exports Catalog class

- package-lock.json
- package.json
- src/util/file-util.ts
Signed-off-by: Noé Samaille <noe.samaille@ibm.com>
> Removes memory-stream which cause circular dep

- .github/workflows/npm-publish.yaml
- package.json
Signed-off-by: NoeSamaille <noe.samaille@ibm.com>
> Updates npm-publish workflow with build

- package-lock.json
- package.json
- src/services/catalog-loader/index.ts
- src/services/iascable/index.ts
- src/services/module-selector/index.ts
Signed-off-by: Noé Samaille <noe.samaille@ibm.com>
> Updates exports for consuming iascable as library

- src/models/variables.model.ts
- src/util/terraform/terraform-file.ts
- Adds JSON parse and stringify logic for variables of type map(string) - closes #287
> Fixes handling of map(string) variables

- examples/infra-ibmcloud-quickstart-portworx.yaml
- package.json
- src/commands/iascable-build.ts
- src/services/iascable/iascable.impl.ts
- Formats folders created from solution and BOM names to use lower-case values with spaces replaced by dashes - closes #294
> Fixes directory names in generated output

- README.md
- install.sh
Signed-off-by: Rich Ehrhardt <rich_ehrhardt@au1.ibm.com>
> Adds support to install on M1 Macbooks

- src/models/terragrunt.model.ts
- src/services/iascable/iascable.impl.ts
> Fix prefix and variable names for gitops layer integration

- src/services/iascable/iascable.impl.ts
> Handle empty path returned from writer
